FROM nvcr.io/nvidia/tritonserver:24.10-py3

RUN apt update && apt-get install -y ffmpeg

WORKDIR /workspace
COPY requirements.txt /workspace/requirements.txt
COPY serve /workspace/serve

# Install only the required packages for our simplified model
RUN pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com tensorrt-llm==0.15.0.dev2024110500 && \
    pip install tritonclient[all] && \
    pip install -r requirements.txt && \
    chmod +x /workspace/serve

# Define environment variables
ENV PATH="/workspace:${PATH}"

# Run serve
ENTRYPOINT []
CMD ["serve"]
